arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - LinJ
    - RevJ1
    - RevJ2
    - RevJ3
    - RevJ4
    - RevJ5
    - HandGripper
  gains:
    LinJ:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RevJ1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RevJ2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RevJ3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RevJ4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RevJ5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    HandGripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - FingerL
    - FingerR
  gains:
    FingerL:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FingerR:
      p: 100
      d: 1
      i: 1
      i_clamp: 1