arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Mani_J0
    - Mani_J1
    - Mani_J2
    - Mani_J3
    - Mani_J4
    - Mani_J5
    - Mani_J6
  gains:
    Mani_J0:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J1:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J2:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J3:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J4:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J5:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    Mani_J6:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - FingerL
    - FingerR
  gains:
    FingerL:
      p: 500
      d: 50
      i: 1
      i_clamp: 1
    FingerR:
      p: 500
      d: 50
      i: 1
      i_clamp: 1