controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # arm_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster
    
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
    joints:
      - Mani_J0
      - Mani_J1
      - Mani_J2
      - Mani_J3
      - Mani_J4
      - Mani_J5
      - Mani_J6

    gains:
        Mani_J0: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        Mani_J1: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        Mani_J2: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
        Mani_J3: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        Mani_J4: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
        Mani_J5: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
        Mani_J6: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }

gripper_controller:
  ros__parameters:
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
    joints:
      - FingerR
      - FingerL

    gains:
        Mani_J0: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        Mani_J1: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
